export const FETCH_CATEGORY_START = 'FETCH_CATEGORY_START'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAIL = 'FETCH_CATEGORY_FAIL'

export const FETCH_UPLOAD_LIST_START = 'FETCH_UPLOAD_LIST_START'
export const FETCH_UPLOAD_LIST_SUCCESS = 'FETCH_UPLOAD_LIST_SUCCESS'
export const FETCH_UPLOAD_LIST_FAIL = 'FETCH_UPLOAD_LIST_FAIL'

export const FETCH_PENDING_LIST_START = 'FETCH_PENDING_LIST_START'
export const FETCH_PENDING_LIST_SUCCESS = 'FETCH_PENDING_LIST_SUCCESS'
export const FETCH_PENDING_LIST_FAIL = 'FETCH_PENDING_LIST_FAIL'

export const FETCH_REJECTED_LIST_START = 'FETCH_REJECTED_LIST_START'
export const FETCH_REJECTED_LIST_SUCCESS = 'FETCH_REJECTED_LIST_SUCCESS'
export const FETCH_REJECTED_LIST_FAIL = 'FETCH_REJECTED_LIST_FAIL'

export const FETCH_TRENDING_LIST_START = 'FETCH_TRENDING_LIST_START'
export const FETCH_TRENDING_LIST_SUCCESS = 'FETCH_TRENDING_LIST_SUCCESS'
export const FETCH_TRENDING_LIST_FAIL = 'FETCH_TRENDING_LIST_FAIL'

export const FETCH_FUNNY_LIST_START = 'FETCH_FUNNY_LIST_START'
export const FETCH_FUNNY_LIST_SUCCESS = 'FETCH_FUNNY_LIST_SUCCESS'
export const FETCH_FUNNY_LIST_FAIL = 'FETCH_FUNNY_LIST_FAIL'

export const FETCH_STUDENT_LIST_START = 'FETCH_STUDENT_LIST_START'
export const FETCH_STUDENT_LIST_SUCCESS = 'FETCH_STUDENT_LIST_SUCCESS'
export const FETCH_STUDENT_LIST_FAIL = 'FETCH_STUDENT_LIST_FAIL'

export const FETCH_FAVOURITE_LIST_START = 'FETCH_FAVOURITE_LIST_START'
export const FETCH_FAVOURITE_LIST_SUCCESS = 'FETCH_FAVOURITE_LIST_SUCCESS'
export const FETCH_FAVOURITE_LIST_FAIL = 'FETCH_FAVOURITE_LIST_FAIL'

export const TOGGLE_FAVOURITE_START = "TOGGLE_FAVOURITE_START"
export const TOGGLE_FAVOURITE_SUCCESS = "TOGGLE_FAVOURITE_SUCCESS"
export const TOGGLE_FAVOURITE_FAIL = "TOGGLE_FAVOURITE_FAIL"

export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';



export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL';

export const UPLOAD_POST_START = 'UPLOAD_POST_START';
export const UPLOAD_POST_SUCCESS = 'UPLOAD_POST_SUCCESS';
export const UPLOAD_POST_FAIL = 'UPLOAD_POST_FAIL';

export const SEARCH_POST_START = 'SEARCH_POST_START';
export const SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS';
export const SEARCH_POST_FAIL = 'SEARCH_POST_FAIL';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';


